# Site settings
title: Connaissance
email: eclaire.reese@gmail.com
description: "Les mots que j'ai appris"
baseurl: /connaissance
url: "http://emilyreese.github.io/connaissance"

# Build settings
markdown: kramdown
permalink: pretty
